In [8]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]#여기서 변수가 많아지면 힘들어짐 -> 그래서 매트릭스로 곱!!!

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)###feed하기 위해 플레이스 홀더로 만들고
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')##웨이트에 변수를 할당
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(5000):#학습을 시킴
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  19614.8
Prediction:
 [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]
10 Cost:  14.0682
Prediction:
 [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]

 ...

1990 Cost:  4.9197
Prediction:
 [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]
2000 Cost:  4.89449
Prediction:
 [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]
'''

0 Cost:  247611.3 
Prediction:
 [-288.2666  -347.1585  -341.47778 -373.70288 -263.62128]
10 Cost:  3.5732765 
Prediction:
 [151.91841 181.91837 179.82684 193.98546 139.93242]
20 Cost:  1.3012911 
Prediction:
 [153.24641 183.5218  181.40292 195.70241 141.15674]
30 Cost:  1.2960967 
Prediction:
 [153.24657 183.52927 181.4065  195.70692 141.16371]
40 Cost:  1.2909368 
Prediction:
 [153.24274 183.53192 181.4053  195.70627 141.167  ]
50 Cost:  1.2858056 
Prediction:
 [153.23888 183.53453 181.4041  195.7056  141.17027]
60 Cost:  1.2807047 
Prediction:
 [153.23505 183.53716 181.40291 195.70491 141.17354]
70 Cost:  1.275646 
Prediction:
 [153.23123 183.53975 181.40172 195.70424 141.17679]
80 Cost:  1.2705925 
Prediction:
 [153.22742 183.54233 181.4005  195.70357 141.18004]
90 Cost:  1.2655652 
Prediction:
 [153.22359 183.54492 181.3993  195.70288 141.18326]
100 Cost:  1.2605791 
Prediction:
 [153.2198  183.5475  181.39813 195.70221 141.18651]
110 Cost:  1.2556088 
Prediction:
 [153.21602 183.5

1000 Cost:  0.9045385 
Prediction:
 [152.91632 183.75385 181.30292 195.65044 141.4429 ]
1010 Cost:  0.9014597 
Prediction:
 [152.91333 183.75586 181.30196 195.64992 141.44539]
1020 Cost:  0.898403 
Prediction:
 [152.91037 183.75787 181.30103 195.64944 141.4479 ]
1030 Cost:  0.89536685 
Prediction:
 [152.90742 183.7599  181.30011 195.64897 141.4504 ]
1040 Cost:  0.8923437 
Prediction:
 [152.90445 183.7619  181.29918 195.64848 141.45285]
1050 Cost:  0.8893174 
Prediction:
 [152.90149 183.76392 181.29823 195.64798 141.45532]
1060 Cost:  0.8863238 
Prediction:
 [152.89856 183.76591 181.29732 195.64752 141.45781]
1070 Cost:  0.8833436 
Prediction:
 [152.89561 183.76791 181.2964  195.64703 141.46027]
1080 Cost:  0.8803762 
Prediction:
 [152.89268 183.7699  181.29547 195.64655 141.46272]
1090 Cost:  0.87743443 
Prediction:
 [152.88977 183.77188 181.29456 195.64607 141.46515]
1100 Cost:  0.87449396 
Prediction:
 [152.88686 183.77386 181.29364 195.6456  141.4676 ]
1110 Cost:  0.87157726 
Predic

2020 Cost:  0.6612297 
Prediction:
 [152.64915 183.93506 181.21857 195.60834 141.66483]
2030 Cost:  0.65941924 
Prediction:
 [152.64688 183.93663 181.21785 195.60802 141.66672]
2040 Cost:  0.6576359 
Prediction:
 [152.6446  183.93817 181.21715 195.6077  141.6686 ]
2050 Cost:  0.6558641 
Prediction:
 [152.64233 183.93968 181.21642 195.60735 141.67044]
2060 Cost:  0.65408546 
Prediction:
 [152.64008 183.94122 181.21568 195.60701 141.67229]
2070 Cost:  0.6523298 
Prediction:
 [152.63782 183.94276 181.215   195.60667 141.67416]
2080 Cost:  0.65057963 
Prediction:
 [152.63556 183.94427 181.21426 195.60632 141.67598]
2090 Cost:  0.6488222 
Prediction:
 [152.63333 183.94583 181.21356 195.60602 141.67786]
2100 Cost:  0.6470955 
Prediction:
 [152.63109 183.94731 181.21283 195.60568 141.67967]
2110 Cost:  0.64536685 
Prediction:
 [152.62885 183.94884 181.21213 195.60535 141.6815 ]
2120 Cost:  0.64365053 
Prediction:
 [152.62662 183.95035 181.21143 195.60503 141.68333]
2130 Cost:  0.64194643 
Pre

3040 Cost:  0.51840454 
Prediction:
 [152.44464 184.07341 181.15349 195.57976 141.83086]
3050 Cost:  0.51734275 
Prediction:
 [152.44289 184.0746  181.15294 195.57953 141.83226]
3060 Cost:  0.5162861 
Prediction:
 [152.44116 184.07578 181.15237 195.57932 141.83365]
3070 Cost:  0.5152379 
Prediction:
 [152.4394  184.07695 181.15182 195.57907 141.83505]
3080 Cost:  0.51419365 
Prediction:
 [152.43768 184.07812 181.15128 195.57886 141.83644]
3090 Cost:  0.5131363 
Prediction:
 [152.43594 184.0793  181.1507  195.57864 141.83781]
3100 Cost:  0.51211655 
Prediction:
 [152.43422 184.08044 181.15016 195.57843 141.83919]
3110 Cost:  0.5110854 
Prediction:
 [152.43251 184.08162 181.14961 195.5782  141.84058]
3120 Cost:  0.5100523 
Prediction:
 [152.43079 184.08278 181.14905 195.57799 141.84193]
3130 Cost:  0.5090304 
Prediction:
 [152.42908 184.08394 181.1485  195.57777 141.8433 ]
3140 Cost:  0.5080202 
Prediction:
 [152.42735 184.08508 181.14795 195.57753 141.84467]
3150 Cost:  0.5070089 
Predi

4010 Cost:  0.43677235 
Prediction:
 [152.29446 184.17467 181.10526 195.56203 141.94931]
4020 Cost:  0.43611377 
Prediction:
 [152.29309 184.17557 181.10478 195.56186 141.95033]
4030 Cost:  0.4354651 
Prediction:
 [152.29173 184.17648 181.10435 195.56174 141.95139]
4040 Cost:  0.43481216 
Prediction:
 [152.29036 184.1774  181.10391 195.5616  141.95244]
4050 Cost:  0.43416986 
Prediction:
 [152.28903 184.1783  181.10345 195.56143 141.95349]
4060 Cost:  0.4335351 
Prediction:
 [152.28766 184.1792  181.10303 195.56128 141.95451]
4070 Cost:  0.43289632 
Prediction:
 [152.28633 184.18011 181.1026  195.56116 141.95557]
4080 Cost:  0.43226314 
Prediction:
 [152.285   184.18103 181.10219 195.56105 141.95662]
4090 Cost:  0.43163085 
Prediction:
 [152.28366 184.18192 181.10173 195.56088 141.95764]
4100 Cost:  0.43100867 
Prediction:
 [152.28233 184.18282 181.10132 195.56076 141.95868]
4110 Cost:  0.43038282 
Prediction:
 [152.281   184.1837  181.10088 195.56062 141.95969]
4120 Cost:  0.42976412 

4970 Cost:  0.38656333 
Prediction:
 [152.1784  184.25253 181.0675  195.55133 142.03755]
4980 Cost:  0.3861534 
Prediction:
 [152.17734 184.25327 181.06717 195.55124 142.03833]
4990 Cost:  0.3857415 
Prediction:
 [152.17627 184.25395 181.06679 195.55113 142.03912]


'\n0 Cost:  19614.8\nPrediction:\n [ 21.69748688  39.10213089  31.82624626  35.14236832  32.55316544]\n10 Cost:  14.0682\nPrediction:\n [ 145.56100464  187.94958496  178.50236511  194.86721802  146.08096313]\n\n ...\n\n1990 Cost:  4.9197\nPrediction:\n [ 148.15084839  186.88632202  179.6293335   195.81796265  144.46044922]\n2000 Cost:  4.89449\nPrediction:\n [ 148.15931702  186.8805542   179.63194275  195.81971741  144.45298767]\n'

In [10]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  7105.46
Prediction:
 [[ 80.82241058]
 [ 92.26364136]
 [ 93.70250702]
 [ 98.09217834]
 [ 72.51759338]]
10 Cost:  5.89726
Prediction:
 [[ 155.35159302]
 [ 181.85691833]
 [ 181.97254944]
 [ 194.21760559]
 [ 140.85707092]]

...

1990 Cost:  3.18588
Prediction:
 [[ 154.36352539]
 [ 182.94833374]
 [ 181.85189819]
 [ 194.35585022]
 [ 142.03240967]]
2000 Cost:  3.1781
Prediction:
 [[ 154.35881042]
 [ 182.95147705]
 [ 181.85035706]
 [ 194.35533142]
 [ 142.036026  ]]

'''


0 Cost:  32002.895 
Prediction:
 [[315.73944]
 [371.2775 ]
 [369.9186 ]
 [404.34726]
 [279.93808]]
10 Cost:  24.14031 
Prediction:
 [[157.5286 ]
 [181.15381]
 [182.5689 ]
 [200.32942]
 [134.92894]]
20 Cost:  23.728567 
Prediction:
 [[157.03209]
 [180.59084]
 [181.99666]
 [199.7076 ]
 [134.50685]]
30 Cost:  23.610157 
Prediction:
 [[157.0128 ]
 [180.60138]
 [181.98956]
 [199.7012 ]
 [134.5222 ]]
40 Cost:  23.492285 
Prediction:
 [[156.995  ]
 [180.61363]
 [181.98418]
 [199.69666]
 [134.53883]]
50 Cost:  23.375118 
Prediction:
 [[156.97726]
 [180.62585]
 [181.97882]
 [199.69212]
 [134.55542]]
60 Cost:  23.258564 
Prediction:
 [[156.95956]
 [180.63805]
 [181.9735 ]
 [199.68764]
 [134.57198]]
70 Cost:  23.142664 
Prediction:
 [[156.94193]
 [180.6502 ]
 [181.96815]
 [199.68312]
 [134.58846]]
80 Cost:  23.027374 
Prediction:
 [[156.92435]
 [180.66235]
 [181.96286]
 [199.67865]
 [134.60492]]
90 Cost:  22.912699 
Prediction:
 [[156.90681]
 [180.67445]
 [181.9576 ]
 [199.6742 ]
 [134.62135]]
10

850 Cost:  15.777575 
Prediction:
 [[155.7054 ]
 [181.50294]
 [181.5957 ]
 [199.3638 ]
 [135.74963]]
860 Cost:  15.7017765 
Prediction:
 [[155.69121]
 [181.51274]
 [181.59145]
 [199.36009]
 [135.76302]]
870 Cost:  15.626389 
Prediction:
 [[155.67706]
 [181.52249]
 [181.58719]
 [199.35638]
 [135.77637]]
880 Cost:  15.551356 
Prediction:
 [[155.66296]
 [181.53224]
 [181.58295]
 [199.35268]
 [135.78969]]
890 Cost:  15.47674 
Prediction:
 [[155.6489 ]
 [181.54196]
 [181.57872]
 [199.349  ]
 [135.80298]]
900 Cost:  15.402524 
Prediction:
 [[155.63483]
 [181.55162]
 [181.57448]
 [199.34528]
 [135.8162 ]]
910 Cost:  15.32869 
Prediction:
 [[155.62085]
 [181.5613 ]
 [181.57028]
 [199.34161]
 [135.82942]]
920 Cost:  15.255289 
Prediction:
 [[155.60689]
 [181.57092]
 [181.56609]
 [199.33795]
 [135.84259]]
930 Cost:  15.1823 
Prediction:
 [[155.59299]
 [181.58054]
 [181.5619 ]
 [199.3343 ]
 [135.85573]]
940 Cost:  15.10965 
Prediction:
 [[155.57912]
 [181.59012]
 [181.55775]
 [199.33066]
 [135.86

1730 Cost:  10.443286 
Prediction:
 [[154.59543]
 [182.26944]
 [181.2627 ]
 [199.06778]
 [136.80206]]
1740 Cost:  10.395876 
Prediction:
 [[154.5843 ]
 [182.27715]
 [181.25935]
 [199.06476]
 [136.8127 ]]
1750 Cost:  10.348842 
Prediction:
 [[154.57323]
 [182.28482]
 [181.25606]
 [199.06175]
 [136.82327]]
1760 Cost:  10.30197 
Prediction:
 [[154.56213]
 [182.29245]
 [181.25272]
 [199.05872]
 [136.83382]]
1770 Cost:  10.255368 
Prediction:
 [[154.55112]
 [182.30008]
 [181.24944]
 [199.05571]
 [136.84436]]
1780 Cost:  10.209022 
Prediction:
 [[154.54013]
 [182.30771]
 [181.24615]
 [199.05273]
 [136.85487]]
1790 Cost:  10.162928 
Prediction:
 [[154.52914]
 [182.31528]
 [181.24286]
 [199.04971]
 [136.86533]]
1800 Cost:  10.117081 
Prediction:
 [[154.5182 ]
 [182.32283]
 [181.23958]
 [199.04674]
 [136.87578]]
1810 Cost:  10.07147 
Prediction:
 [[154.50731]
 [182.3304 ]
 [181.23634]
 [199.04376]
 [136.8862 ]]
1820 Cost:  10.026106 
Prediction:
 [[154.49641]
 [182.3379 ]
 [181.23306]
 [199.040

'\n0 Cost:  7105.46\nPrediction:\n [[ 80.82241058]\n [ 92.26364136]\n [ 93.70250702]\n [ 98.09217834]\n [ 72.51759338]]\n10 Cost:  5.89726\nPrediction:\n [[ 155.35159302]\n [ 181.85691833]\n [ 181.97254944]\n [ 194.21760559]\n [ 140.85707092]]\n\n...\n\n1990 Cost:  3.18588\nPrediction:\n [[ 154.36352539]\n [ 182.94833374]\n [ 181.85189819]\n [ 194.35585022]\n [ 142.03240967]]\n2000 Cost:  3.1781\nPrediction:\n [[ 154.35881042]\n [ 182.95147705]\n [ 181.85035706]\n [ 194.35533142]\n [ 142.036026  ]]\n\n'

In [17]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)##loadtxt사용해서 데이터 불러오기
x_data = xy[:, 0:-1]#2차원 행렬, x와 y를 나누는 슬라이싱 ##넘파이의 슬라이싱 및 인덱스!!
#전체 행에걸 다가져오고 대신 처음부터 마지막 한개를 제외해서 !, 이걸 x 데이터라하겠다

y_data = xy[:, [-1]]##-1에 리스트를 쓰지 않을경우 (25,)로 나오고 리스트를 써서 계산하면 (25,1)이나옴
#즉 shape이 달려지기 때문에 matrix계산을 하려고 하는 것임
#전체 다가져오는데 마지막 한 열만 가져옴 이걸 y라하겠다.

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

# train output
'''
0 Cost: 21027.0 
Prediction:
 [[22.048063 ]
 [21.619772 ]
 ...
 [31.36112  ]
 [24.986364 ]]
10 Cost: 95.976326 
Prediction:
 [[157.11063 ]
 [183.99283 ]
 ...
 [167.48862 ]
 [193.25117 ]]
 1990 Cost: 24.863274 
Prediction:
 [[154.4393  ]
 [185.5584  ]
 ...
 [158.27443 ]
 [192.79778 ]]
2000 Cost: 24.722485 
Prediction:
 [[154.42894 ]
 [185.5586  ]
 ...
 [158.24257 ]
 [192.79166 ]]
'''
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))###예측해보는것 x1= 100 ,x2= 70,x3=101일떄 몇이 나올지 
                                                                    #학습한 모델로 예측

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[ 181.73277283]]
Other scores will be  [[ 145.86265564]
 [ 187.23129272]]

'''

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[152. 185. 180. 196. 142. 101. 149. 115. 175. 164. 141. 141. 184. 152.
 148. 192. 147. 183. 177. 159. 177. 175. 175. 149. 192.] 
y_data shape: (25,)


ValueError: Cannot feed value of shape (25,) for Tensor 'Placeholder_27:0', which has shape '(?, 1)'

In [29]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data
##Queue Runners 
#여러개의 많은 파일을 읽고싶을때 텐서플로우에선 이걸 큐에다가 저장을하고 읽어온다음 배치형태로 쓰고 내보냄 하나씩 그래서 메모리 차지 적어짐
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')#파일 여러개 입력가능 리스트안에 이름 주루룩 입력하면됨

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)##큐에서 읽어오기 
print(key)
print(value)
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]#,를기준으로 나눠짐
xy = tf.decode_csv(value, record_defaults=record_defaults)#파일에서 값으로 읽어옴 csv파일을 읽음

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)#이 데이터로 베치를 하라 이러면 한번에 10개씩 가져옴(batch_size)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')##shape항상 맞춰줘야함
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
#쓰레드는 병렬처리시, 메모리를 아끼기 위해 사용 

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])#데이터가져오기
    cost_val, hy_val, _ = sess.run(###이 두변수를 feed로 넘겨주면됨
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)#쓰레이드에서 join은 다른 것이 끝날때까지 기다리는 함수 

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[185.33531]]
Other scores will be  [[178.36246]
 [177.03687]]
'''


Tensor("ReaderReadV2_6:0", shape=(), dtype=string)
Tensor("ReaderReadV2_6:1", shape=(), dtype=string)
0 Cost:  51375.52 
Prediction:
 [[-55.65454 ]
 [-80.45697 ]
 [-72.236115]
 [-81.25903 ]
 [-62.23557 ]
 [-50.745174]
 [-60.313194]
 [-43.762863]
 [-81.12753 ]
 [-81.58908 ]]
10 Cost:  85.459755 
Prediction:
 [[159.84357]
 [178.65463]
 [183.01572]
 [196.75517]
 [135.38365]
 [ 95.00295]
 [147.79944]
 [110.52909]
 [161.08583]
 [142.8252 ]]
20 Cost:  73.25961 
Prediction:
 [[161.26357]
 [180.42236]
 [184.72462]
 [198.63338]
 [136.73294]
 [ 96.03117]
 [149.21358]
 [111.58715]
 [162.77292]
 [144.43102]]
30 Cost:  72.546646 
Prediction:
 [[161.23904 ]
 [180.4534  ]
 [184.72266 ]
 [198.64813 ]
 [136.75769 ]
 [ 96.082596]
 [149.2328  ]
 [111.61107 ]
 [162.83664 ]
 [144.53285 ]]
40 Cost:  71.90169 
Prediction:
 [[161.20493]
 [180.47263]
 [184.70917]
 [198.65031]
 [136.7734 ]
 [ 96.12722]
 [149.24257]
 [111.62794]
 [162.88914]
 [144.62411]]
50 Cost:  71.26302 
Prediction:
 [[161.1709 ]
 [180.4917 

490 Cost:  48.328896 
Prediction:
 [[159.81625]
 [181.25182]
 [184.15927]
 [198.73442]
 [137.4125 ]
 [ 97.93808]
 [149.63406]
 [112.30506]
 [165.01962]
 [148.32593]]
500 Cost:  47.909634 
Prediction:
 [[159.78847]
 [181.2674 ]
 [184.14828]
 [198.73608]
 [137.42532]
 [ 97.97427]
 [149.6418 ]
 [112.31847]
 [165.06221]
 [148.39986]]
510 Cost:  47.49424 
Prediction:
 [[159.76083]
 [181.28293]
 [184.13734]
 [198.73775]
 [137.43808]
 [ 98.01032]
 [149.64954]
 [112.33181]
 [165.10461]
 [148.47346]]
520 Cost:  47.082684 
Prediction:
 [[159.73332]
 [181.29842]
 [184.12646]
 [198.7394 ]
 [137.45082]
 [ 98.0462 ]
 [149.65721]
 [112.34509]
 [165.14682]
 [148.54674]]
530 Cost:  46.675068 
Prediction:
 [[159.70592]
 [181.3138 ]
 [184.11563]
 [198.74101]
 [137.46349]
 [ 98.08191]
 [149.66487]
 [112.35829]
 [165.18883]
 [148.61966]]
540 Cost:  46.27108 
Prediction:
 [[159.67865]
 [181.32915]
 [184.10486]
 [198.74266]
 [137.4761 ]
 [ 98.11746]
 [149.67247]
 [112.37145]
 [165.23067]
 [148.69229]]
550 Co

990 Cost:  31.520096 
Prediction:
 [[158.57051 ]
 [181.95335 ]
 [183.66743 ]
 [198.80852 ]
 [137.9908  ]
 [ 99.561844]
 [149.97899 ]
 [112.90049 ]
 [166.93013 ]
 [151.63965 ]]
1000 Cost:  31.258137 
Prediction:
 [[158.54836]
 [181.96585]
 [183.6587 ]
 [198.80981]
 [138.00114]
 [ 99.59073]
 [149.98505]
 [112.91096]
 [166.9641 ]
 [151.69853]]
1010 Cost:  30.998646 
Prediction:
 [[158.52628 ]
 [181.9783  ]
 [183.65001 ]
 [198.81111 ]
 [138.01144 ]
 [ 99.61946 ]
 [149.99109 ]
 [112.921364]
 [166.99792 ]
 [151.75713 ]]
1020 Cost:  30.741552 
Prediction:
 [[158.50432]
 [181.9907 ]
 [183.64134]
 [198.81241]
 [138.0217 ]
 [ 99.64809]
 [149.9971 ]
 [112.93173]
 [167.0316 ]
 [151.81548]]
1030 Cost:  30.486944 
Prediction:
 [[158.48247]
 [182.00305]
 [183.63275]
 [198.81369]
 [138.0319 ]
 [ 99.67658]
 [150.00308]
 [112.94204]
 [167.06512]
 [151.87355]]
1040 Cost:  30.23471 
Prediction:
 [[158.46068]
 [182.01532]
 [183.62416]
 [198.81494]
 [138.04205]
 [ 99.70494]
 [150.00902]
 [112.95231]
 [167.0

1470 Cost:  21.368498 
Prediction:
 [[157.61176 ]
 [182.49553 ]
 [183.2902  ]
 [198.86435 ]
 [138.44025 ]
 [100.8109  ]
 [150.23895 ]
 [113.348236]
 [168.39987 ]
 [154.18378 ]]
1480 Cost:  21.2024 
Prediction:
 [[157.5939  ]
 [182.50563 ]
 [183.28319 ]
 [198.86537 ]
 [138.44867 ]
 [100.834145]
 [150.24374 ]
 [113.35646 ]
 [168.42723 ]
 [154.23108 ]]
1490 Cost:  21.037884 
Prediction:
 [[157.57613]
 [182.5157 ]
 [183.2762 ]
 [198.86638]
 [138.45703]
 [100.85729]
 [150.24849]
 [113.36465]
 [168.45445]
 [154.27817]]
1500 Cost:  20.874878 
Prediction:
 [[157.55844 ]
 [182.52574 ]
 [183.26927 ]
 [198.8674  ]
 [138.4654  ]
 [100.88034 ]
 [150.25323 ]
 [113.372795]
 [168.48158 ]
 [154.32506 ]]
1510 Cost:  20.713457 
Prediction:
 [[157.54085]
 [182.53574]
 [183.26237]
 [198.86844]
 [138.47371]
 [100.90328]
 [150.25797]
 [113.3809 ]
 [168.50859]
 [154.37173]]
1520 Cost:  20.553558 
Prediction:
 [[157.52328]
 [182.54565]
 [183.25548]
 [198.86942]
 [138.48196]
 [100.92611]
 [150.26263]
 [113.3889

Your score will be  [[171.5856]]
Other scores will be  [[164.66652]
 [186.62175]]


'\nYour score will be  [[185.33531]]\nOther scores will be  [[178.36246]\n [177.03687]]\n'