In [1]:
# Lab 6 Softmax Classifier
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]###4개의 x
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]###3개의 class 3개중하나를 선택해야함 이걸 선택하기 위해선 (one-hot-encoding) 정답인 자리만 1로 한다.

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])##shape 조심 class가 3개이기 때문에 
nb_classes = 3 

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')#[4,np_clases] 들어오는 값 나가는 값
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)####softmax 구현 !! 

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))###cross_entropy-error

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:#session을 열고 학습을 시키는 과정
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

'''
0 6.926112
200 0.6005015
400 0.47295815
600 0.37342924
800 0.28018373
1000 0.23280522
1200 0.21065344
1400 0.19229904
1600 0.17682323
1800 0.16359556
2000 0.15216158
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]
-------------
[[0.9311919  0.06290216 0.00590591]] [0]
-------------
[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]
-------------
[[1.3890490e-03 9.9860185e-01 9.0613084e-06]
 [9.3119192e-01 6.2902197e-02 5.9059085e-03]
 [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]
'''

0 6.926112
200 0.6005018
400 0.4729582
600 0.37342912
800 0.2801835
1000 0.23280513
1200 0.21065336
1400 0.192299
1600 0.1768232
1800 0.16359553
2000 0.1521616
--------------
[[1.3890432e-03 9.9860197e-01 9.0612402e-06]] [1]
--------------
[[0.93119204 0.06290206 0.00590588]] [0]
--------------
[[1.2732767e-08 3.3411323e-04 9.9966586e-01]] [2]
--------------
[[1.3890432e-03 9.9860197e-01 9.0612402e-06]
 [9.3119204e-01 6.2902056e-02 5.9058843e-03]
 [1.2732767e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]


'\n0 6.926112\n200 0.6005015\n400 0.47295815\n600 0.37342924\n800 0.28018373\n1000 0.23280522\n1200 0.21065344\n1400 0.19229904\n1600 0.17682323\n1800 0.16359556\n2000 0.15216158\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]] [1]\n-------------\n[[0.9311919  0.06290216 0.00590591]] [0]\n-------------\n[[1.2732815e-08 3.3411323e-04 9.9966586e-01]] [2]\n-------------\n[[1.3890490e-03 9.9860185e-01 9.0613084e-06]\n [9.3119192e-01 6.2902197e-02 5.9059085e-03]\n [1.2732815e-08 3.3411323e-04 9.9966586e-01]] [1 0 2]\n'

In [2]:
# Lab 6 Softmax Classifier
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

# Predicting animal type based on various features
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]#데이터 읽어오기 

print(x_data.shape, y_data.shape)

'''
(101, 16) (101, 1)
'''

nb_classes = 7  # 0 ~ 6

X = tf.placeholder(tf.float32, [None, 16])#여기선 7개이기때문에 None은 7로 자동으로 될것!
Y = tf.placeholder(tf.int32, [None, 1])  # 0 ~ 6

Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
print("one_hot:", Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])#원핫은 reshape해야함!!!원핫을하게되면  한차원이 더 더해짐 !!! 그래서 차원하나를 빼야함
#즉 원핫을 하게 되면 rank가 +1이됨 
print("reshape one_hot:", Y_one_hot)

'''
one_hot: Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape one_hot: Tensor("Reshape:0", shape=(?, 7), dtype=float32)
'''

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

# Cross entropy cost/loss
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                                 labels=tf.stop_gradient([Y_one_hot])))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)##argmax는 one_hot_encoding에서 최고로 높은 값을 불러줌 ,1은 어떤축을 기준으로 할것인가.
#예측한 값이 맞는지 틀린지 알고싶음@!!!
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))##예측한 것과 one-hot 정답 레이블과 비교 !
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))###맞게 예측한것들을 모아서 정확도를 구함

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        _, cost_val, acc_val = sess.run([optimizer, cost, accuracy], feed_dict={X: x_data, Y: y_data})
                                        
        if step % 100 == 0:
            print("Step: {:5}\tCost: {:.3f}\tAcc: {:.2%}".format(step, cost_val, acc_val))

    # Let's see if we can predict
    pred = sess.run(prediction, feed_dict={X: x_data})
    # y_data: (N,1) = flatten => (N, ) matches pred.shape
    for p, y in zip(pred, y_data.flatten()):#zip으로 묶음 각각의 엘리먼트를 [p,y]로 보내는것!!
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

'''
Step:     0 Loss: 5.106 Acc: 37.62%
Step:   100 Loss: 0.800 Acc: 79.21%
Step:   200 Loss: 0.486 Acc: 88.12%#스탭을하면서 loss는 줄어들고 정확도는 계속 높아짐
...
Step:  1800	Loss: 0.060	Acc: 100.00%
Step:  1900	Loss: 0.057	Acc: 100.00%
Step:  2000	Loss: 0.054	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
...
[True] Prediction: 0 True Y: 0
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
'''

(101, 16) (101, 1)
one_hot: Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape one_hot: Tensor("Reshape:0", shape=(?, 7), dtype=float32)
Step:     0	Cost: 4.144	Acc: 25.74%
Step:   100	Cost: 0.654	Acc: 79.21%
Step:   200	Cost: 0.418	Acc: 87.13%
Step:   300	Cost: 0.308	Acc: 92.08%
Step:   400	Cost: 0.245	Acc: 95.05%
Step:   500	Cost: 0.205	Acc: 95.05%
Step:   600	Cost: 0.176	Acc: 97.03%
Step:   700	Cost: 0.154	Acc: 98.02%
Step:   800	Cost: 0.137	Acc: 98.02%
Step:   900	Cost: 0.123	Acc: 98.02%
Step:  1000	Cost: 0.112	Acc: 99.01%
Step:  1100	Cost: 0.103	Acc: 99.01%
Step:  1200	Cost: 0.094	Acc: 100.00%
Step:  1300	Cost: 0.088	Acc: 100.00%
Step:  1400	Cost: 0.082	Acc: 100.00%
Step:  1500	Cost: 0.076	Acc: 100.00%
Step:  1600	Cost: 0.072	Acc: 100.00%
Step:  1700	Cost: 0.068	Acc: 100.00%
Step:  1800	Cost: 0.064	Acc: 100.00%
Step:  1900	Cost: 0.061	Acc: 100.00%
Step:  2000	Cost: 0.058	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y

'\nStep:     0 Loss: 5.106 Acc: 37.62%\nStep:   100 Loss: 0.800 Acc: 79.21%\nStep:   200 Loss: 0.486 Acc: 88.12%\n...\nStep:  1800\tLoss: 0.060\tAcc: 100.00%\nStep:  1900\tLoss: 0.057\tAcc: 100.00%\nStep:  2000\tLoss: 0.054\tAcc: 100.00%\n[True] Prediction: 0 True Y: 0\n[True] Prediction: 0 True Y: 0\n[True] Prediction: 3 True Y: 3\n...\n[True] Prediction: 0 True Y: 0\n[True] Prediction: 6 True Y: 6\n[True] Prediction: 1 True Y: 1\n'